/* 🤖 this file was generated by svg-to-ts*/
export const appSecond: {
  name: "second";
  data: string;
} = {
  name: "second",
  data: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 48 48"><path fill="none" d="M0 0h48v48H0z"/><path d="M37 22v-7c0-7.2-5.8-13-13-13S11 7.8 11 15v7H6v18.5c0 1.3.8 2.4 2 2.8 2.3.8 8.4 2.7 16 2.7s13.7-1.9 16-2.7c1.2-.4 2-1.6 2-2.8V22h-5zm-22-7c0-5 4-9 9-9s9 4 9 9v7H15v-7zm23 24.7c-2.2.7-7.6 2.3-14 2.3s-11.8-1.5-14-2.3V26h28v13.7z"/></svg>`
};
